### ISSUE TITLE
익명화 모듈(프로그램)에 대한 질문

### ISSUE THREAD

**Issue by JB0527** [ni-inha/De-identification-of-Korean-names-in-clinical-notes#1]
익명화 프로세스를 읽어보았는데, 대부분이 이 형식에 따르는 지 아니면 점차 수정하거나 데이터셋마다 보완할 점이 필요할 지 궁금합니다.  추가로 FREETEXT_COL = "emr_NSGREC" 이 부분이 이해가 되지 않습니다.  이외에는 패턴을 이해한 것 같습니다!

또한 익명화를 진행하려는 원본 데이터는 그때 말한 inception에서 admin으로 부터 추출한 데이터인지 아님 아예 처음보는 데이터인지 헷갈려서 질문남깁니다!

**Comment by oneonlee** [comment]
> 익명화 프로세스를 읽어보았는데, 대부분이 이 형식에 따르는 지 아니면 점차 수정하거나 데이터셋마다 보완할 점이 필요할 지 궁금합니다. 

대부분 이 형식에 따르지만, 모든 데이터가 전부 익명화되지 않을 수 있습니다.
따라서 추가로 수정하거나, 데이터셋마다 보완을 한다면 좋긴 하겠습니**다만**,

**해당 프로그램의 성능에 대해서는 이미 검토가 완료되었으므로, 현시점에서의 규칙의 추가 및 보완은 필요 없어보입니다.**

**Comment by JB0527** [comment]
감사합니다! 이 후는 그렇게 올리겠습니다!

**Comment by oneonlee** [comment]
> 추가로 FREETEXT_COL = "emr_NSGREC" 이 부분이 이해가 되지 않습니다. 

`FREETEXT_COL`값은 엑셀 데이터 중 익명화를 원하는 freetext가 들어있는 "열의 이름"을 나타내는 변수입니다.

사용자에게 입력을 받으며, 아무 것도 입력하지 않으면 `"emr_NSGREC"` 라는 값을 기본으로 사용하도록 설계하였습니다.

**Comment by oneonlee** [comment]
> 또한 익명화를 진행하려는 원본 데이터는 그때 말한 inception에서 admin으로 부터 추출한 데이터인지 아님 아예 처음보는 데이터인지 헷갈려서 질문남깁니다!

`그때 말한 inception에서 admin으로 부터 추출한 데이터`라는게 저는 무엇인지 잘 모르겠네요.

본 익명화 프로그램은 어떤 데이터던 간에 사용할 수 있도록 설계하였습니다.

다만, 현 시점에서 사용될 데이터는, 실제 병원의 EMR 데이터입니다.

**Comment by JB0527** [comment]
질문에 대한 응답을 모두 이해했습니다! 이 이슈는 close 하겠습니다! 감사합니다.
